name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

      - name: generate sha for nx commands
      - uses: nrwl/nx-set-shas@v3

      - name: Install dependencies
        run: pnpm install

      - run: pnpm exec nx format:check
      - run: pnpm exec nx affected -t lint --parallel=3
      - run: pnpm exec nx affected -t test --parallel=3 --configuration=ci
      - run: pnpm exec nx affected -t build --parallel=3