name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

      - uses: nrwl/nx-set-shas@v3
      - name: Install dependencies
        run: pnpm install
      
      - name: Lint step
        run: npx nx affected -t lint --parallel=3

      - name: Test Step
        run: npx nx affected -t test --parallel=3 --configuration=ci

      - name: Build step
        run: npx nx affected -t build --parallel=3